/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoconRouteImport } from './routes/nocon'
import { Route as ConRouteImport } from './routes/con'
import { Route as IndexRouteImport } from './routes/index'

const NoconRoute = NoconRouteImport.update({
  id: '/nocon',
  path: '/nocon',
  getParentRoute: () => rootRouteImport,
} as any)
const ConRoute = ConRouteImport.update({
  id: '/con',
  path: '/con',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/con': typeof ConRoute
  '/nocon': typeof NoconRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/con': typeof ConRoute
  '/nocon': typeof NoconRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/con': typeof ConRoute
  '/nocon': typeof NoconRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/con' | '/nocon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/con' | '/nocon'
  id: '__root__' | '/' | '/con' | '/nocon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConRoute: typeof ConRoute
  NoconRoute: typeof NoconRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nocon': {
      id: '/nocon'
      path: '/nocon'
      fullPath: '/nocon'
      preLoaderRoute: typeof NoconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/con': {
      id: '/con'
      path: '/con'
      fullPath: '/con'
      preLoaderRoute: typeof ConRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConRoute: ConRoute,
  NoconRoute: NoconRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
